groups:
  Utility_Krumpac_Armors:
  - Krump_Armor_Belt_Troll
  - Krump_Armor_Belt_Leather
  Legs_Krumpac_Armors:
  - Krump_T1_Armor_Slave_Legs
  - Krump_T3_Armor_Boar_Legs
  - Krump_T2_Armor_Boar_Legs
  - Krump_T1_Armor_Boar_Legs
  - Krump_T1_Armor_Deer_Legs
  - Krump_T2_Armor_Deer_Legs
  - Krump_T3_Armor_Eikthyr_Legs
  - Krump_T1_Armor_Troll_Legs
  - Krump_T2_Armor_Troll_Legs
  - Krump_T3_Armor_Troll_Legs
  - Krump_T1_Armor_Bronze_Legs
  - Krump_T2_Armor_Bronze_Legs
  - Krump_T3_Armor_Bronze_Legs
  - Krump_T1_Armor_BoneMass_Legs
  - Krump_T2_Armor_BoneMass_Legs
  - Krump_T3_Armor_BoneMass_Legs
  - Krump_T1_Armor_Berserkir_Legs
  - Krump_T2_Armor_Berserkir_Legs
  - Krump_T3_Armor_Berserkir_Legs
  - Krump_T1_Armor_Tribe_Legs
  - Krump_T2_Armor_Tribe_Legs
  - Krump_T3_Armor_Tribe_Legs
  - Krump_T1_Armor_Yagluth_Legs
  - Krump_T2_Armor_Yagluth_Legs
  - Krump_T3_Armor_Yagluth_Legs
  Chest_Krumpac_Armors:
  - Krump_T1_Armor_Slave_Chest
  - Krump_T3_Armor_Boar_Chest
  - Krump_T2_Armor_Boar_Chest
  - Krump_T1_Armor_Boar_Chest
  - Krump_T1_Armor_Deer_Chest
  - Krump_T2_Armor_Deer_Chest
  - Krump_T3_Armor_Eikthyr_Chest
  - Krump_T1_Armor_Troll_Chest
  - Krump_T2_Armor_Troll_Chest
  - Krump_T3_Armor_Troll_Chest
  - Krump_T1_Armor_Bronze_Chest
  - Krump_T2_Armor_Bronze_Chest
  - Krump_T3_Armor_Bronze_Chest
  - Krump_T1_Armor_BoneMass_Chest
  - Krump_T2_Armor_BoneMass_Chest
  - Krump_T3_Armor_BoneMass_Chest
  - Krump_T1_Armor_Berserkir_Chest
  - Krump_T2_Armor_Berserkir_Chest
  - Krump_T3_Armor_Berserkir_Chest
  - Krump_T1_Armor_Tribe_Chest
  - Krump_T2_Armor_Tribe_Chest
  - Krump_T3_Armor_Tribe_Chest
  - Krump_T1_Armor_Yagluth_Chest
  - Krump_T2_Armor_Yagluth_Chest
  - Krump_T3_Armor_Yagluth_Chest
  - Krump_Armor_Druid_Chest_01
  - Krump_Armor_Druid_Chest_02
  - Krump_Armor_Druid_Chest_03
  - Krump_Armor_Jarl_Chest_01
  - Krump_Armor_NPC_Chest_01
  - Krump_Armor_NPC_Chest_02
  - Krump_Armor_NPC_Chest_03
  Helmet_Krumpac_Armors:
  - Krump_T1_Armor_Slave_Hat
  - Krump_T3_Armor_Boar_Helmet
  - Krump_T2_Armor_Boar_Helmet
  - Krump_T1_Armor_Boar_Helmet
  - Krump_T1_Armor_Deer_Helmet
  - Krump_T2_Armor_Deer_Helmet
  - Krump_T3_Armor_Eikthyr_Helmet
  - Krump_T1_Armor_Troll_Helmet
  - Krump_T2_Armor_Troll_Helmet
  - Krump_T3_Armor_Troll_Helmet
  - Krump_T1_Armor_Bronze_Helmet
  - Krump_T2_Armor_Bronze_Helmet
  - Krump_T3_Armor_Bronze_Helmet
  - Krump_T1_Armor_BoneMass_Helmet
  - Krump_T2_Armor_BoneMass_Helmet
  - Krump_T3_Armor_BoneMass_Helmet
  - Krump_T1_Armor_Berserkir_Helmet
  - Krump_T2_Armor_Berserkir_Helmet
  - Krump_T3_Armor_Berserkir_Helmet
  - Krump_T1_Armor_Tribe_Helmet
  - Krump_T2_Armor_Tribe_Helmet
  - Krump_T3_Armor_Tribe_Helmet
  - Krump_T1_Armor_Yagluth_Helmet
  - Krump_T2_Armor_Yagluth_Helmet
  - Krump_T3_Armor_Yagluth_Helmet
  - Krump_Armor_Jarl_Helmet_01
  - Krump_Armor_NPC_Helmet_02
  - Krump_Armor_NPC_Helmet_03
  - Krump_Armor_NPC_Helmet_04
  - Krump_Armor_NPC_Helmet_05
  Shoulder_Krumpac_Armors:
  - Krump_Armor_Cape_Bonemass
