groups:
  Material_Krumpac_Dungeon_Meadows:
  - Krump_Mat_Daughters_Head
  - Krump_Mat_Salt_Rock
  Trophie_Krumpac_Dungeon_Meadows:
  - Krump_Mat_Trophy_Nokken
  - Krump_Mat_Trophy_Neck_Brute
  Misc_Krumpac_Dungeon_Meadows:
  - Krump_Mat_Key_Neck_Cave
