groups:
  OneHandedWeapon_Krumpac_Reforge_Core:
  - Krump_Wep_Harpoon_Copper
  - Krump_Wep_Axe_Copper
  - Krump_Wep_Dagger_Copper
  - Krump_Wep_Mace_Copper
  - Krump_Wep_Spear_Copper
  - Krump_Wep_Sword_Copper
  - Krump_Wep_Knife_Butcher
  TwoHandedWeapon_Krumpac_Reforge_Core:
  - Krump_Wep_BattleAxe_Copper
  - Krump_Wep_GreatSword_Copper
  - Krump_Wep_Sledge_Copper
  - Krump_Wep_Pickaxe_Antler2
  - Krump_Wep_Pickaxe_Bronze2
  - Krump_Wep_Pickaxe_Iron3
  - Krump_Wep_FishingRod_03
  Bow_Krumpac_Reforge_Core:
  - Krump_Wep_Bow_Copper
  Shield_Krumpac_Reforge_Core:
  - Krump_Wep_Shield_Great_Copper
  - Krump_Wep_Shield_Small_Copper_1
  - Krump_Wep_Shield_Small_Copper_2
  Material_Krumpac_Reforge_Core:
  - Krump_Mat_Wood_Ancient_Bark
  - Krump_Mat_Cotton_Net
  - Krump_Mat_Feathers
  - Krump_Mat_Tar
  - Krump_Mat_Bear_Fur
  - Krump_Mat_Bear_Tooth
  - Krump_Mat_Shovel_Coal
  - Krump_Mat_Tin_Heated
  - Krump_Mat_Tin_Ingot
  - Krump_Mat_Tin_Bloom
  - Krump_Mat_Tin_Lump
  - Krump_Mat_Tin_Plate
  - Krump_Mat_Copper_Heated
  - Krump_Mat_Copper_Ingot
  - Krump_Mat_Copper_Bloom
  - Krump_Mat_Copper_Lump
  - Krump_Mat_Copper_Plate
  - Krump_Mat_Ancient_Tree_Sap
  - Krump_Mat_Bronze_Heated
  - Krump_Mat_Bronze_Ingot
  - Krump_Mat_Bronze_Bloom
  - Krump_Mat_Bronze_Bloom_Heated
  - Krump_Mat_Bronze_Lump
  - Krump_Mat_Bronze_Lump_Heated
  - Krump_Mat_Iron_Heated
  - Krump_Mat_Iron_Ingot
  - Krump_Mat_Iron_Bloom
  - Krump_Mat_Iron_Bloom_Heated
  - Krump_Mat_Iron_Lump
  - Krump_Mat_Iron_Lump_Heated
  - Krump_Mat_Iron_Plate
  - Krump_Mat_Iron_Plate_Heated
  - Krump_Mat_Iron_Chest_Fragment
  - Krump_Mat_Iron_Helmet_Fragment
  - Krump_Mat_Iron_Legs_Fragment
  - Krump_Mat_Silver_Heated
  - Krump_Mat_Silver_Ingot
  - Krump_Mat_Silver_Bloom
  - Krump_Mat_Silver_Lump
  - Krump_Mat_Silver_Plate
  - Krump_Mat_Silver_Plate_Fragment_Small
  - Krump_Mat_Silver_Nails_Heated
  - Krump_Mat_Silver_Needle_Heated
  - Krump_Mat_Silver_Bloom_Heated
  - Krump_Mat_Silver_Lump_Heated
  - Krump_Mat_Silver_Plate_Heated
  - Krump_Mat_Silver_Needle
  - Krump_Mat_Silver_Nails
  - Krump_Mat_Silver_Plate_Fragment_Small_Heated
  - Krump_Mat_Silver_Wire_Heated
  - Krump_Mat_Bone_Bonemass
  - Krump_Mat_Silver_Chest_Fragment
  - Krump_Mat_Silver_Helmet_Fragment
  - Krump_Mat_Scale_Dragon
  - Krump_Mat_Silver_Legs_Fragment
  - Krump_Mat_Steel_Heated
  - Krump_Mat_Steel_Ingot
  - Krump_Mat_Steel_Bloom
  - Krump_Mat_Steel_Lump
  - Krump_Mat_Steel_Plate
  - Krump_Mat_Steel_Nails_Heated
  - Krump_Mat_Steel_Needle_Heated
  - Krump_Mat_Steel_Fragment_Plate_Big
  - Krump_Mat_Steel_Bloom_Heated
  - Krump_Mat_Steel_Lump_Heated
  - Krump_Mat_Steel_Plate_Heated
  - Krump_Mat_Steel_Needle
  - Krump_Mat_Steel_Nails
  - Krump_Mat_Steel_Plate_Fragment_Small
  - Krump_Mat_Steel_Plate_Fragment_Small_Heated
  - Krump_Mat_Steel_Wire_Heated
  - Krump_Mat_Steel_Chest_Fragment
  - Krump_Mat_Steel_Helmet_Fragment
  - Krump_Mat_Steel_Legs_Fragment
  - Krump_Mat_Needle_Chitin
  - Krump_Mat_Nails_Chitin
  - Krump_Mat_Nails_Bone
  - Krump_Mat_Needle_Bone
  - Krump_Mat_Bronze_Needle
  - Krump_Mat_Bronze_Nails
  - Krump_Mat_Iron_Nails
  - Krump_Mat_Iron_Nails_Heated
  - Krump_Mat_Bronze_Needle_Heated
  - Krump_Mat_Bronze_Nails_Heated
  - Krump_Mat_Iron_Needle_Heated
  - Krump_Mat_Iron_Needle
  - Krump_Mat_Coal
  - Krump_Mat_Charcoal
  - Krump_Mat_Bucket_Water
  - Krump_Mat_Bucket_Empty
  - Krump_Mat_Thrall_Clay
  - Krump_Mat_Thrall_CoreWood
  - Krump_Mat_Thrall_FineWood
  - Krump_Mat_Thrall_Hay
  - Krump_Mat_Thrall_Stone
  - Krump_Mat_Thrall_Wood
  - Krump_Mat_Thrall_Oil
  - Krump_Mat_Treasure_Meadows_Scroll_01
  - Krump_Mat_Treasure_Meadows_Scroll_02
  - Krump_Mat_Treasure_Meadows_Scroll_03
  - Krump_Mat_Treasure_Meadows_Scroll_04
  - Krump_Mat_Treasure_Meadows_Scroll_05
  - Krump_Mat_Treasure_Meadows_Scroll_06
  - Krump_Mat_Treasure_Meadows_Scroll_07
  - Krump_Mat_Treasure_Meadows_Scroll_08
  - Krump_Mat_Treasure_BlackForest_Scroll_01
  - Krump_Mat_Treasure_BlackForest_Scroll_02
  - Krump_Mat_Treasure_BlackForest_Scroll_03
  - Krump_Mat_Treasure_BlackForest_Scroll_04
  - Krump_Mat_Treasure_BlackForest_Scroll_05
  - Krump_Mat_Treasure_Ocean_Scroll_01
  - Krump_Mat_Treasure_Ocean_Scroll_02
  - Krump_Mat_Treasure_Ocean_Scroll_03
  - Krump_Mat_Treasure_Ocean_Scroll_04
  - Krump_Mat_Treasure_Mountains_Scroll_01
  - Krump_Mat_Treasure_Mountains_Scroll_02
  - Krump_Mat_Treasure_Mountains_Scroll_03
  - Krump_Mat_Treasure_Mountains_Scroll_04
  - Krump_Mat_Treasure_Plains_Scroll_01
  - Krump_Mat_Treasure_Plains_Scroll_02
  - Krump_Mat_Treasure_Plains_Scroll_03
  - Krump_Mat_Treasure_Plains_Scroll_04
  - Krump_Mat_Bronze_Plate_Fragment
  - Krump_Mat_Bronze_Plate_Fragment_Heated
  - Krump_Mat_Bronze_Plate_Fragment_Small_Heated
  - Krump_Mat_Bronze_Plate_Fragment_Small
  - Krump_Mat_Iron_Plate_Fragment_Small
  - Krump_Mat_Lydit_Shaped
  - Krump_Mat_Iron_Plate_Fragment_Small_Heated
  - Krump_Mat_Lydit_Fragments
  - Krump_Mat_Hide_Boar_Dried
  - Krump_Mat_Hide_Deer_Dried
  - Krump_Mat_Hide_Eikthyr_Dried
  - Krump_Mat_Hide_Troll_Dried
  - Krump_Mat_Hide_Wolf_Dried
  - Krump_Mat_Hide_Eikthyr
  - Krump_Mat_Sticks_Wood_01
  - Krump_Mat_Leather_Strip
  - Krump_Mat_Copper_Wire
  - Krump_Mat_Bronze_Wire
  - Krump_Mat_Bronze_Wire_Heated
  - Krump_Mat_Iron_Wire
  - Krump_Mat_Iron_Wire_Heated
  - Krump_Mat_Silver_Wire
  - Krump_Mat_Steel_Wire
  - Krump_Mat_Handle_CoreWood
  - Krump_Mat_Handle_FineWood
  - Krump_Mat_Ancient_Handle_Small
  - Krump_Mat_Ancient_Handle_Big
  - Krump_Mat_Palm_Handle_Small
  - Krump_Mat_Palm_Handle_Big
  - Krump_Mat_Urchin_Thistle
  - Krump_Mat_HardAntler
  - Krump_Mat_BoneFragments_Bloody
  - Krump_Mat_BoneFragments_Clean
  - Krump_Mat_BoneFragments_Powder
  - Krump_Mat_Sulfur
  - Krump_Mat_Steelfire
  - Krump_Mat_Steelfired_Iron
  - Krump_Mat_Greydwarf_Pitch
  - Krump_Mat_Shovel_Clay
  - Krump_Mat_Shovel_Sandstone
  - Krump_Mat_Shovel_Snow
  - Krump_Mat_Shovel_Bricks
  - Krump_Mat_Greydwarfeye_Shaped
  - Krump_Mat_Shovel_Clay_Bricks_Unfired
  - Krump_Mat_Shovel_Clay_Tile_Unfired
  - Krump_Mat_Shovel_Clay_Tile_Fired
  - Krump_Mat_Shovel_Stone_Shaped
  - Krump_Mat_Slave_Food_Animal_Fat
  - Krump_Mat_Slave_Food_Bread
  - Krump_Mat_Slave_Food_Rotten_Rat
  - Krump_Mat_Slave_Food_Rat
  - Krump_Mat_Cotton_Raw
  - Krump_Mat_Hay
  - Krump_Mat_Straw
  - Krump_Mat_Wheat
  - Krump_Mat_Jute_Seeds
  - Krump_Mat_Jute_Dried
  - Krump_Mat_Jute_Fabric
  - Krump_Mat_Jute_Fresh
  - Krump_Mat_Cotton_Seeds
  - Krump_Mat_Wheat_Seeds
  - Krump_Mat_Chitin
  - Krump_Mat_Chitin_Abyssal
  - Krump_Mat_Whale_Meat
  - Krump_Mat_Cotton_Cloth
  - Krump_Mat_Thread_Empty
  - Krump_Mat_Thread_Cotton
  - Krump_Mat_Rope
  - Krump_Mat_Cotton
  - Krump_Mat_Straw_Bundle
  - Krump_Mat_Rope_Straw
  - Krump_Mat_Hide_Boar
  - Krump_Mat_Leather_Thick
  - Krump_Mat_Hide_Deer
  - Krump_Mat_Leather_Scraps
  - Krump_Mat_Glue
  - Krump_Mat_Leather
  - Krump_Mat_Leather_Troll
  - Krump_Mat_Mast_Gokstad
  - Krump_Mat_Mast_Knarr
  - Krump_Mat_Mast_Njord
  - Krump_Mat_Elder_Roots
  - Krump_Mat_SharpeningStone
  - Krump_Mat_Plank_Wood
  - Krump_Mat_Plank_FineWood
  - Krump_Mat_Plank_CoreWood
  - Krump_Mat_Plank_AncientWood
  - Krump_Mat_Plank_PalmWood
  - Krump_Mat_Wood_Palm
  - Krump_Mat_Hook_Fish
  Misc_Krumpac_Reforge_Core:
  - Krump_Spawner_CryptKey
  - Krump_Spawner_EikthyrKey
  - Krump_Spawner_BoneMass_Key
  Tool_Krumpac_Reforge_Core:
  - Krump_Wep_Shovel
  Helmet_Krumpac_Reforge_Core:
  - Krump_Mat_Skull_Eikthyr
  - Krump_Mat_Skull_Deer
  - Krump_Mat_Skull_Neck
  - Krump_Mat_Skull_Boar
  - Krump_Mat_Skull_Troll
  - Krump_Mat_Skull_Wolf
  - Krump_Mat_Skull_Draugr
  - Krump_Mat_Skull_Draugr_Fem
  - Krump_Mat_Skull_Draugr_Elite
  Trophie_Krumpac_Reforge_Core:
  - Krump_Mat_Trophy_Fenring
  - Krump_Mat_Trophy_Wolf
  - Krump_Mat_Trophy_Skeleton_Clean
  - Krump_Mat_Trophy_Skeleton_Bloody
  - Krump_Mat_Trophy_Draugr
  - Krump_Mat_Trophy_Draugr_Fem
  - Krump_Mat_Trophy_Draugr_Elite
  - Krump_Mat_Trophy_Skeleton_Poison_Bloody
  - Krump_Mat_Trophy_Skeleton_Poison_Clean
  - Krump_Mat_Trophy_Fish01
  - Krump_Mat_Trophy_Fish02
  - Krump_Mat_Trophy_Fish03
  - Krump_Mat_Trophy_Fish04
  - Krump_Mat_Trophy_Fish05
  - Krump_Mat_Trophy_Fish06
  - Krump_Mat_Trophy_Fish07
  - Krump_Mat_Trophy_Fish08
  - Krump_Mat_Trophy_Fish09
  - Krump_Mat_Trophy_Fish10
  - Krump_Mat_Trophy_Fish11
  - Krump_Mat_Trophy_Fish12
  - Krump_Mat_Trophy_Fish13
  - Krump_Mat_Trophy_Fish14
  - Krump_Mat_Trophy_Fish15
  - Krump_Mat_Trophy_Whale
  - Krump_Mat_Trophy_Leviathan
  - Krump_Mat_Trophy_Shark01
  Consumable_Krumpac_Reforge_Core:
  - Krump_Mat_Worms
  - Krump_Vanilla_Replaced
  - Krump_Mat_Crab_Meat
  - Krump_Mat_Crab_Raw
  - Krump_Mat_Fish_01_Dried
  - Krump_Mat_Fish_02_Dried
  - Krump_Mat_Fish_03_Dried
  - Krump_Mat_Fish_04_Dried
  - Krump_Mat_Fish_05_Dried
  - Krump_Mat_Fish_06_Dried
  - Krump_Mat_Fish_07_Dried
  - Krump_Mat_Fish_08_Dried
  - Krump_Mat_Fish_09_Dried
  - Krump_Mat_Fish_10_Dried
  - Krump_Mat_Fish_11_Dried
  - Krump_Mat_Fish_12_Dried
  - Krump_Mat_Fish_13_Dried
  - Krump_Mat_Fish_14_Dried
  - Krump_Mat_Fish_15_Dried
  - Krump_Mat_Whale_Meat_Dried
  - Krump_Mat_Fish_Shark_Meat_Dried
  - Krump_Mat_Fish_01_Raw
  - Krump_Mat_Fish_02_Raw
  - Krump_Mat_Fish_03_Raw
  - Krump_Mat_Fish_04_Raw
  - Krump_Mat_Fish_05_Raw
  - Krump_Mat_Fish_06_Raw
  - Krump_Mat_Fish_07_Raw
  - Krump_Mat_Fish_08_Raw
  - Krump_Mat_Fish_09_Raw
  - Krump_Mat_Fish_10_Raw
  - Krump_Mat_Fish_11_Raw
  - Krump_Mat_Fish_12_Raw
  - Krump_Mat_Fish_13_Raw
  - Krump_Mat_Fish_14_Raw
  - Krump_Mat_Fish_15_Raw
  - Krump_Mat_Oil_Fish
  - Krump_Mat_Oil_Ancient
  - Krump_Mat_Oil_Vegetable
  Ammo_Krumpac_Reforge_Core:
  - Krump_Mat_Arrow_Copper
  - Krump_Mat_Arrow_Wood
  - Krump_Mat_Arrow_Lydit
  - Krump_Mat_Arrow_Bone
  - Krump_Mat_Arrow_Bronze
  - Krump_Mat_Arrow_Chitin
  - Krump_Mat_Arrow_Iron
  - Krump_Mat_Arrow_Silver
  - Krump_Mat_Arrow_Steel
  - Krump_Mat_Arrow_Bone_Frozen
  - Krump_Mat_Arrow_Bronze_Frozen
  - Krump_Mat_Arrow_Chitin_Frozen
  - Krump_Mat_Arrow_Copper_Frozen
  - Krump_Mat_Arrow_Iron_Frozen
  - Krump_Mat_Arrow_Lydit_Frozen
  - Krump_Mat_Arrow_Silver_Frozen
  - Krump_Mat_Arrow_Steel_Frozen
  - Krump_Mat_Arrow_Wood_Frozen
  - Krump_Mat_Arrow_Bone_Fire
  - Krump_Mat_Arrow_Bone_Fire_3
  - Krump_Mat_Arrow_Bronze_Fire
  - Krump_Mat_Arrow_Chitin_Fire
  - Krump_Mat_Arrow_Copper_Fire
  - Krump_Mat_Arrow_Iron_Fire
  - Krump_Mat_Arrow_Lydit_Fire
  - Krump_Mat_Arrow_Silver_Fire
  - Krump_Mat_Arrow_Steel_Fire
  - Krump_Mat_Arrow_Wood_Fire
  - Krump_Mat_FishingBaits_RawFish
  - Krump_Mat_FishingBaits_NeckTails
  - Krump_Mat_FishingBaits_Forest
  - Krump_Mat_FishingBaits_Entrails
  - Krump_Mat_FishingBaits_Chicken
  - Krump_Mat_FishingBaits_Dragon
  - Krump_Mat_FishingBaits_Vermin
  - Krump_Mat_FishingBaits_Wolf
  Torch_Krumpac_Reforge_Core:
  - Krump_Wep_Torch
