groups:
  Material_Datys_Professions:
  - D_BeechSeeds
  - D_FirCone
  - D_PineCone
  - D_Acorn
  - D_BirchSeeds
  - D_Cotton
  - D_Cotton_Seeds
  - D_Hay
  - D_Hay_Seeds
  - D_Jute
  - D_Jute_Seeds
  - D_BASE_CarrotSoup
  - D_BASE_MushroomSoup
  - D_BASE_VenBroth
  - D_Master_T1_recipe
  - D_small_Cook_Bless
  - D_Small_Food_Supply_1
  - D_Small_Food_Supply_2
  - D_Small_Food_Supply_3
  - D_Master_T2_recipe
  - D_Small_Food_Supply_4
  - D_Small_Food_Supply_5
  - D_Small_Food_Supply_6
  - D_Food_recipe6
  - D_Food_recipe7
  - D_Food_recipe8
  - D_Food_recipe9
  - D_Food_recipeBF1
  - D_Food_recipeBF2
  - D_Food_recipeBF3
  - D_Food_recipeBF4
  - D_Barrel_Wood
  - D_Burned_Meat
  - D_Wood_Plate_small
  - D_Bronze_Plate
  - D_Bronze_Skewer
  - D_Burned_Food
  - D_Stone_Bowl
  - D_Boar_Leg
  - D_Boar_Meat
  - D_Boar_Rib
  - D_Pork_Leg
  - D_Pork_Meat
  - D_Pork_Rib
  - D_Deer_Leg
  - D_Deer_Meat
  - D_Deer_Rib
  - D_NeckTail
  - D_Honeycomb
  - D_Candle
  - D_BeeWax
  - D_Raspberry_Seedling
  - D_BlessedRaspberry_Seedling
  - D_Blueberry_Seedling
  - D_BlessBlueberry_Seedling
  - D_Blackberry_Seedling
  - D_BlessedBlackberry_Seedling
  - D_Blessed_AppleBranch
  - D_Apple_Branch
  - D_Blessed_PlumBranch
  - D_Plum_Branch
  - D_Walnut_BlessedBranch
  - D_Walnut_Branch
  - D_Orange_BlessBranch
  - D_Orange_Branch
  - D_Lemon_BlessedBranch
  - D_Lemon_Branch
  - D_Dandelion
  - D_Dandelion_Seeds
  - D_BlessedDandelion_Seeds
  - D_Potato_Seeds
  - D_Carrot_Seeds
  - D_Turnip_Seeds
  - D_Pumpkin_Seeds
  - D_Mushroom_Spore
  - D_BlessedMushroom_Spore
  - D_YMushroom_Spore
  - D_BlessYellowMushroom_Spore
  - D_Swampshroom_Spore
  - D_BlessSwampshroom_Spore
  - D_Gut_Crab
  - D_Gut_Carp
  - D_Gut_Unicorn_Fish
  - D_Gut_Barracuda
  - D_Gut_trewavasae
  - D_Gut_Piranha
  - D_Gut_Siganus
  - D_Chives
  - D_Chives_Seeds
  - D_Chives_crushed
  - D_Chervil
  - D_Chervil_Seeds
  - D_Chervil_crushed
  - D_Levander
  - D_Levander_Seeds
  - D_Rosemary
  - D_Rosemary_Seeds
  - D_Thistle
  - D_Catharanthus
  - D_Catharanthus_Seeds
  - D_Erigeron
  - D_Erigeron_Seeds
  - D_Eitr_Elx_Base
  - D_Eitr_Pot_Base
  - D_Healing_Elx_Base
  - D_Healing_Pot_Base
  - D_Stamina_Elx_Base
  - D_Stamina_Pot_Base
  - D_Carry_Pot_Base
  - D_PoisonResist_Base
  - D_Carry_Pot_Base_N
  - D_PoisonResist_Base_N
  - D_FrostResist_Base
  - D_Eitr_Elx_Base_N
  - D_Eitr_Pot_Base_N
  - D_Healing_Elx_Base_N
  - D_Healing_Pot_Base_N
  - D_Stamina_Elx_Base_N
  - D_Stamina_Pot_Base_N
  - D_Dandelion_crushed
  - D_Mushroom_crushed
  - D_Small_Leather_Bag
  - D_Leather_Bag
  - D_TrollLeather_Bag
  - D_Rosemary_crushed
  - D_Levander_crushed
  - D_Thistle_crushed
  - D_YMushroom_crushed
  - D_Troll_Bone
  - D_Erigeron_crushed
  - D_G_mushroom_crushed
  - D_Catharanthus_crushed
  - D_Empty_Vial_small
  - D_Empty_Vial_Small2
  Consumable_Datys_Professions:
  - D_Meadows_Food1
  - D_Meadows_Food2
  - D_Meadows_Food3
  - D_Meadows_Food4
  - D_Meadows_Food5
  - D_Meadows_Food6
  - D_Meadows_Food7
  - D_Meadows_Food8
  - D_Meadows_Food9
  - D_BForest_Food1
  - D_BForest_Food2
  - D_BForest_Food4
  - D_BForest_Food3
  - D_BForest_Food5
  - D_BForest_Food6
  - D_BForest_Food7
  - D_BForest_Food8
  - D_BForest_Food9
  - D_BForest_Food10
  - D_BForest_Food11
  - D_Raspberry_Juice
  - D_Meadows_Juice
  - D_Hot_Raspberrys
  - D_Dandelion_Tea
  - D_Apple_Juice
  - D_Blueberry_juice
  - D_Orange_juice
  - D_Thistle_tea
  - D_BlackForest_Juice
  - D_Glazed_Apples
  - D_Carrot_juice
  - D_Water
  - D_Boiled_Water
  - D_Boar_Leg_Roasted
  - D_Boar_Meat_Roasted
  - D_Boar_Rib_Roasted
  - D_Pork_Leg_Roasted
  - D_Pork_Meat_Roasted
  - D_Pork_Rib_Roasted
  - D_Deer_Leg_Roasted
  - D_Deer_Meat_Roasted
  - D_Deer_Rib_Roasted
  - D_NeckTail_Roasted
  - D_Honey
  - D_Raspberry
  - D_Blueberrys
  - D_Blackberry
  - D_Apple
  - D_Apple_Baked
  - D_Plum
  - D_Walnut
  - D_Walnut_Core
  - D_Orange
  - D_Orange_Cutt
  - D_Lemon
  - D_Lemon_Cutt
  - D_Potato
  - D_Potato_Roasted
  - D_Potato_Cut
  - D_Potato_Cut_Roasted
  - D_Carrot
  - D_Carrot_Cut
  - D_Carrot_Boiled_Cut
  - D_Carrot_Boiled
  - D_Turnip
  - D_Turnip_Cut
  - D_Pumpkin
  - D_Mushroom
  - D_Mushroom_Cutt
  - D_Mushroom_Roast_Cutt
  - D_Mushroom_Rosated
  - D_Yellow_MushroomRoast
  - D_Yellow_Mushroom
  - D_Yellow_CuttMushroom
  - D_Yellow_RoastMushroom
  - D_Swamp_MushroomRoast
  - D_Swamp_Mushroom
  - D_Swamp_CuttMushroom
  - D_Swamp_CuttRoastMushroom
  - D_Roasted_Crab
  - D_Roasted_Carp
  - D_Roasted_Unicorn_Fish
  - D_Roasted_Barracuda
  - D_Roasted_Treawavasae
  - D_Roasted_Piranha
  - D_Roasted_Siganus
  - D_Ointment_Eitr
  - D_Ointment_Heal
  - D_Ointment_Stamina
  - D_Ointment_Carry
  - D_Eitr_Elixir
  - D_Eitr_Potion
  - D_Healing_Elixir
  - D_Healing_Potion
  - D_Stamin_Elixir
  - D_Stamina_Potion
  - D_Carry_Elixir
  - D_Poison_Elixir_weak
  - D_Carry_Elixir_N
  - D_Poison_Elixir
  - D_Frost_Elixir
  - D_Eitr_ElixirN
  - D_Eitr_PotionN
  - D_Health_ElixirN
  - D_Health_PotionN
  - D_Stamin_ElixirN
  - D_Stamin_PotionN
  Tool_Datys_Professions:
  - D_Cook_Spoon
  - D_Primitive_Plant_Hoe
  - D_FineWood_Plant_Hoe
  - D_Wood_Cultivator
  - D_Iron_Plant_Hoe
  - D_DecorationFoodTool
  OneHandedWeapon_Datys_Professions:
  - D_Bronze_Butcher
  - D_Stone_Butcher
  - D_Wood_Tankard
  - D_CoreWood_Tankard
  - D_Iron_Tankard
  - D_Primitive_Bandage
  - D_Leather_Bandage
  - D_Cotton_Bandage
  - D_Stone_Sickle
  - D_Finewood_Sickle
  - D_Iron_Sickle
  Torch_Datys_Professions:
  - D_Wood_Lantern
  - D_Bronze_Lantern
  - D_Extinguished_Torch
  TwoHandedWeapon_Datys_Professions:
  - D_Lute
  - D_Boar_Carcass
  - D_Deer_Carcass
  Helmet_Datys_Professions:
  - D_Beehat
  - D_Farmet_Hat
  - D_T2Farmet_Hat1
  - D_Bard_Hat
  - D_Herbalist_Hat
  - D_T2Herbalist_Hat
