groups:
  TwoHandedWeapon_Krumpac_Weapon_Arsenal:
  - Krump_Wep_Sledge_Stagbreaker
  - Krump_Wep_Sledge_Iron
  - Krump_Wep_Sledge_Silver
  - Krump_Wep_Sledge_Steel
  - Krump_Wep_Sledge_Bronze
  - Krump_Wep_Atgeir_Lydit
  - Krump_Wep_Atgeir_Bone
  - Krump_Wep_Atgeir_Bronze
  - Krump_Wep_Atgeir_Iron
  - Krump_Wep_GreatSword_Lydit
  - Krump_Wep_GreatSword_Bone
  - Krump_Wep_GreatSword_Bronze
  - Krump_Wep_GreatSword_Chitin
  - Krump_Wep_GreatSword_Iron
  - Krump_Wep_BattleAxe_Lydit
  - Krump_Wep_BattleAxe_Bone
  - Krump_Wep_BattleAxe_Bronze
  - Krump_Wep_BattleAxe_Chitin
  - Krump_Wep_BattleAxe_Iron
  - Krump_Wep_GreatSword_Silver
  - Krump_Wep_BattleAxe_Silver
  - Krump_Wep_Atgeir_Silver
  - Krump_Wep_GreatSword_Steel
  - Krump_Wep_BattleAxe_Steel
  - Krump_Wep_Atgeir_Steel
  OneHandedWeapon_Krumpac_Weapon_Arsenal:
  - Krump_Wep_Harpoon_Bone
  - Krump_Wep_Harpoon_Bronze
  - Krump_Wep_Harpoon_Chitin
  - Krump_Wep_Harpoon_Iron
  - Krump_Wep_Sword_Lydit
  - Krump_Wep_Sword_Bone
  - Krump_Wep_Sword_Bronze
  - Krump_Wep_Sword_Chitin
  - Krump_Wep_Sword_Iron
  - Krump_Wep_Axe_Lydit
  - Krump_Wep_Axe_Bone
  - Krump_Wep_Axe_Bronze
  - Krump_Wep_Axe_Chitin
  - Krump_Wep_Axe_Iron
  - Krump_Wep_Dagger_Lydit
  - Krump_Wep_Dagger_Bone
  - Krump_Wep_Dagger_Bronze
  - Krump_Wep_Dagger_Chitin
  - Krump_Wep_Dagger_Iron
  - Krump_Wep_Spear_Lydit
  - Krump_Wep_Spear_Bone
  - Krump_Wep_Spear_Bronze
  - Krump_Wep_Spear_Chitin
  - Krump_Wep_Spear_Iron
  - Krump_Wep_Mace_Wooden_Club
  - Krump_Wep_Mace_Lydit
  - Krump_Wep_Mace_Bone
  - Krump_Wep_Mace_Bronze
  - Krump_Wep_Mace_Chitin
  - Krump_Wep_Mace_Iron
  - Krump_Wep_Sword_Silver
  - Krump_Wep_Dagger_Silver
  - Krump_Wep_Mace_Silver
  - Krump_Wep_Axe_Silver
  - Krump_Wep_Harpoon_Silver
  - Krump_Wep_Spear_Silver
  - Krump_Wep_Sword_Steel
  - Krump_Wep_Dagger_Steel
  - Krump_Wep_Mace_Steel
  - Krump_Wep_Axe_Steel
  - Krump_Wep_Harpoon_Steel
  - Krump_Wep_Spear_Steel
  Bow_Krumpac_Weapon_Arsenal:
  - Krump_Wep_Bow
  - Krump_Wep_Bow_Lydit
  - Krump_Wep_Bow_Bone
  - Krump_Wep_Bow_Bronze
  - Krump_Wep_Bow_Chitin
  - Krump_Wep_Bow_Bonemass
  - Krump_Wep_Bow_Iron
  - Krump_Wep_Bow_Silver
  - Krump_Wep_Bow_Steel
  Shield_Krumpac_Weapon_Arsenal:
  - Krump_Wep_Shield_Great_Bone
  - Krump_Wep_Shield_Great_Bronze
  - Krump_Wep_Shield_Great_Chitin
  - Krump_Wep_Shield_Great_Iron
  - Krump_Wep_Shield_Small_Wood
  - Krump_Wep_Shield_Small_Lydit
  - Krump_Wep_Shield_Small_Bone_1
  - Krump_Wep_Shield_Small_Bone_2
  - Krump_Wep_Shield_Small_Bronze_1
  - Krump_Wep_Shield_Small_Bronze_2
  - Krump_Wep_Shield_Small_Chitin_1
  - Krump_Wep_Shield_Small_Chitin_2
  - Krump_Wep_Shield_Small_Iron_1
  - Krump_Wep_Shield_Small_Iron_2
  - Krump_Wep_Shield_Great_Lydit
  - Krump_Wep_Shield_Small_Silver_1
  - Krump_Wep_Shield_Small_Silver_2
  - Krump_Wep_Shield_Small_Steel_1
  - Krump_Wep_Shield_Small_Steel_2

